package com.ilargia.games.core.input;

import com.ilargia.games.components.input.BurstMode;
import com.ilargia.games.components.input.Input;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class InputComponentsLookup {

	public static final int BurstMode = 0;
	public static final int Input = 1;
	public static final int totalComponents = 2;

	public static String[] componentNames() {
		return new String[]{"BurstMode", "Input"};
	}

	public static Class[] componentTypes() {
		return new Class[]{BurstMode.class, Input.class};
	}
}