package com.ilargia.games.core.input;

import com.ilargia.games.entitas.api.*;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class InputContext
		extends
			com.ilargia.games.entitas.Context<InputEntity> {

	public InputContext(int totalComponents, int startCreationIndex,
			ContextInfo contextInfo,
			EntityBaseFactory<InputEntity> factoryMethod) {
		super(totalComponents, startCreationIndex, contextInfo, factoryMethod);
	}

	public InputEntity getBurstModeEntity() {
		return getGroup(InputMatcher.BurstMode()).getSingleEntity();
	}

	public boolean isBurstMode() {
		return getBurstModeEntity() != null;
	}

	public InputContext setBurstMode(boolean value) {
		InputEntity entity = getBurstModeEntity();
		if (value != (entity != null)) {
			if (value) {
				entity.setBurstMode(true);
			} else {
				destroyEntity(entity);
			}
		}
		return this;
	}
}