package com.ilargia.games.core;

import com.ilargia.games.entitas.interfaces.IMatcher;
import com.ilargia.games.entitas.matcher.Matcher;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp. Changes to
 * this file may cause incorrect behavior and will be lost.
 * 
 * ---------------------------------------------------------------------------
 */
public class CoreMatcher {

	public static IMatcher _matcherIdentity;
	public static IMatcher _matcherScore;
	public static IMatcher _matcherBounds;
	public static IMatcher _matcherView;
	public static IMatcher _matcherMotion;

	public static IMatcher Identity() {
		if (_matcherIdentity == null) {
			Matcher matcher = (Matcher) Matcher
					.AllOf(CoreComponentIds.Identity);
			matcher.componentNames = CoreComponentIds.componentNames();
			_matcherIdentity = matcher;
		}
		return _matcherIdentity;
	}

	public static IMatcher Score() {
		if (_matcherScore == null) {
			Matcher matcher = (Matcher) Matcher.AllOf(CoreComponentIds.Score);
			matcher.componentNames = CoreComponentIds.componentNames();
			_matcherScore = matcher;
		}
		return _matcherScore;
	}

	public static IMatcher Bounds() {
		if (_matcherBounds == null) {
			Matcher matcher = (Matcher) Matcher.AllOf(CoreComponentIds.Bounds);
			matcher.componentNames = CoreComponentIds.componentNames();
			_matcherBounds = matcher;
		}
		return _matcherBounds;
	}

	public static IMatcher View() {
		if (_matcherView == null) {
			Matcher matcher = (Matcher) Matcher.AllOf(CoreComponentIds.View);
			matcher.componentNames = CoreComponentIds.componentNames();
			_matcherView = matcher;
		}
		return _matcherView;
	}

	public static IMatcher Motion() {
		if (_matcherMotion == null) {
			Matcher matcher = (Matcher) Matcher.AllOf(CoreComponentIds.Motion);
			matcher.componentNames = CoreComponentIds.componentNames();
			_matcherMotion = matcher;
		}
		return _matcherMotion;
	}
}