package com.ilargia.games.core;

import com.ilargia.games.components.Player;
import com.ilargia.games.components.View;
import com.ilargia.games.components.Ball;
import com.ilargia.games.components.Motion;
import com.ilargia.games.components.Score;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class CoreComponentIds {

	public static final int Player = 0;
	public static final int View = 1;
	public static final int Ball = 2;
	public static final int Motion = 3;
	public static final int Score = 4;
	public static final int totalComponents = 5;

	public static String[] componentNames() {
		return new String[]{"Player", "View", "Ball", "Motion", "Score"};
	}

	public static Class[] componentTypes() {
		return new Class[]{Player.class, View.class, Ball.class, Motion.class,
				Score.class};
	}
}