package com.ilargia.games.core;

import com.ilargia.games.components.Ball;
import com.ilargia.games.components.Player;
import com.ilargia.games.components.View;
import com.ilargia.games.components.Motion;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp. Changes to
 * this file may cause incorrect behavior and will be lost.
 * 
 * ---------------------------------------------------------------------------
 */
public class CoreComponentIds {

	public static final int Ball = 0;
	public static final int Player = 1;
	public static final int View = 2;
	public static final int Motion = 3;
	public static final int totalComponents = 4;

	public static String[] componentNames() {
		return new String[]{"Ball", "Player", "View", "Motion"};
	}

	public static Class[] componentTypes() {
		return new Class[]{Ball.class, Player.class, View.class, Motion.class};
	}
}