package com.ilargia.games.core;

import com.ilargia.games.entitas.PoolMetaData;
import com.ilargia.games.entitas.interfaces.IComponent;
import java.util.Stack;
import com.ilargia.games.components.Identity;
import com.ilargia.games.components.Score;
import com.ilargia.games.components.Bounds;
import com.badlogic.gdx.math.Rectangle;
import com.ilargia.games.components.View;
import com.badlogic.gdx.math.Shape2D;
import com.ilargia.games.components.Motion;
import com.badlogic.gdx.math.Vector2;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp. Changes to
 * this file may cause incorrect behavior and will be lost.
 * 
 * ---------------------------------------------------------------------------
 */
public class Entity extends com.ilargia.games.entitas.Entity {

	public Entity(int totalComponents, Stack<IComponent>[] componentPools,
			PoolMetaData poolMetaData) {
		super(totalComponents, componentPools, poolMetaData);
	}

	public Identity getIdentity() {
		return (Identity) getComponent(CoreComponentIds.Identity);
	}

	public boolean hasIdentity() {
		return hasComponent(CoreComponentIds.Identity);
	}

	public void addIdentity(Identity.ID _id) {
		Identity component = createComponent(CoreComponentIds.Identity,
				Identity.class);
		component.id = _id;
		addComponent(CoreComponentIds.Identity, component);
	}

	public void replaceIdentity(Identity.ID _id) {
		Identity component = createComponent(CoreComponentIds.Identity,
				Identity.class);
		component.id = _id;
		replaceComponent(CoreComponentIds.Identity, component);
	}

	public void removeIdentity() {
		removeComponent(CoreComponentIds.Identity);
	}

	public Score getScore() {
		return (Score) getComponent(CoreComponentIds.Score);
	}

	public boolean hasScore() {
		return hasComponent(CoreComponentIds.Score);
	}

	public void addScore(int _value) {
		Score component = createComponent(CoreComponentIds.Score, Score.class);
		component.value = _value;
		addComponent(CoreComponentIds.Score, component);
	}

	public void replaceScore(int _value) {
		Score component = createComponent(CoreComponentIds.Score, Score.class);
		component.value = _value;
		replaceComponent(CoreComponentIds.Score, component);
	}

	public void removeScore() {
		removeComponent(CoreComponentIds.Score);
	}

	public Bounds getBounds() {
		return (Bounds) getComponent(CoreComponentIds.Bounds);
	}

	public boolean hasBounds() {
		return hasComponent(CoreComponentIds.Bounds);
	}

	public void addBounds(Rectangle _rectangle) {
		Bounds component = createComponent(CoreComponentIds.Bounds,
				Bounds.class);
		component.rectangle = _rectangle;
		addComponent(CoreComponentIds.Bounds, component);
	}

	public void replaceBounds(Rectangle _rectangle) {
		Bounds component = createComponent(CoreComponentIds.Bounds,
				Bounds.class);
		component.rectangle = _rectangle;
		replaceComponent(CoreComponentIds.Bounds, component);
	}

	public void removeBounds() {
		removeComponent(CoreComponentIds.Bounds);
	}

	public View getView() {
		return (View) getComponent(CoreComponentIds.View);
	}

	public boolean hasView() {
		return hasComponent(CoreComponentIds.View);
	}

	public void addView(Shape2D _shape) {
		View component = createComponent(CoreComponentIds.View, View.class);
		component.shape = _shape;
		addComponent(CoreComponentIds.View, component);
	}

	public void replaceView(Shape2D _shape) {
		View component = createComponent(CoreComponentIds.View, View.class);
		component.shape = _shape;
		replaceComponent(CoreComponentIds.View, component);
	}

	public void removeView() {
		removeComponent(CoreComponentIds.View);
	}

	public Motion getMotion() {
		return (Motion) getComponent(CoreComponentIds.Motion);
	}

	public boolean hasMotion() {
		return hasComponent(CoreComponentIds.Motion);
	}

	public void addMotion(Vector2 _velocity) {
		Motion component = createComponent(CoreComponentIds.Motion,
				Motion.class);
		component.velocity = _velocity;
		addComponent(CoreComponentIds.Motion, component);
	}

	public void replaceMotion(Vector2 _velocity) {
		Motion component = createComponent(CoreComponentIds.Motion,
				Motion.class);
		component.velocity = _velocity;
		replaceComponent(CoreComponentIds.Motion, component);
	}

	public void removeMotion() {
		removeComponent(CoreComponentIds.Motion);
	}
}