package com.ilargia.games.core;

import com.ilargia.games.entitas.EntityMetaData;
import com.ilargia.games.entitas.interfaces.IComponent;
import java.util.Stack;
import com.ilargia.games.components.Ball;
import com.ilargia.games.components.Score;
import com.ilargia.games.components.Bounds;
import com.badlogic.gdx.math.Rectangle;
import com.ilargia.games.components.Player;
import com.ilargia.games.components.View;
import com.badlogic.gdx.math.Shape2D;
import com.ilargia.games.components.Motion;
import com.badlogic.gdx.math.Vector2;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp. Changes to
 * this file may cause incorrect behavior and will be lost.
 * 
 * ---------------------------------------------------------------------------
 */
public class Entity extends com.ilargia.games.entitas.Entity {

	public Entity(int totalComponents, Stack<IComponent>[] componentPools,
			EntityMetaData entityMetaData) {
		super(totalComponents, componentPools, entityMetaData);
	}

	public Ball getBall() {
		return (Ball) getComponent(CoreComponentIds.Ball);
	}

	public boolean hasBall() {
		return hasComponent(CoreComponentIds.Ball);
	}

	public void addBall(boolean _resetBall) {
		Ball component = createComponent(CoreComponentIds.Ball);
		component.resetBall = _resetBall;
		addComponent(CoreComponentIds.Ball, component);
	}

	public void replaceBall(boolean _resetBall) {
		Ball component = createComponent(CoreComponentIds.Ball);
		component.resetBall = _resetBall;
		replaceComponent(CoreComponentIds.Ball, component);
	}

	public void removeBall() {
		removeComponent(CoreComponentIds.Ball);
	}

	public Score getScore() {
		return (Score) getComponent(CoreComponentIds.Score);
	}

	public boolean hasScore() {
		return hasComponent(CoreComponentIds.Score);
	}

	public void addScore(int _value) {
		Score component = createComponent(CoreComponentIds.Score);
		component.value = _value;
		addComponent(CoreComponentIds.Score, component);
	}

	public void replaceScore(int _value) {
		Score component = createComponent(CoreComponentIds.Score);
		component.value = _value;
		replaceComponent(CoreComponentIds.Score, component);
	}

	public void removeScore() {
		removeComponent(CoreComponentIds.Score);
	}

	public Bounds getBounds() {
		return (Bounds) getComponent(CoreComponentIds.Bounds);
	}

	public boolean hasBounds() {
		return hasComponent(CoreComponentIds.Bounds);
	}

	public void addBounds(Rectangle _rectangle, Bounds.Tag _tag) {
		Bounds component = createComponent(CoreComponentIds.Bounds);
		component.rectangle = _rectangle;
		component.tag = _tag;
		addComponent(CoreComponentIds.Bounds, component);
	}

	public void replaceBounds(Rectangle _rectangle, Bounds.Tag _tag) {
		Bounds component = createComponent(CoreComponentIds.Bounds);
		component.rectangle = _rectangle;
		component.tag = _tag;
		replaceComponent(CoreComponentIds.Bounds, component);
	}

	public void removeBounds() {
		removeComponent(CoreComponentIds.Bounds);
	}

	public Player getPlayer() {
		return (Player) getComponent(CoreComponentIds.Player);
	}

	public boolean hasPlayer() {
		return hasComponent(CoreComponentIds.Player);
	}

	public void addPlayer(Player.ID _id) {
		Player component = createComponent(CoreComponentIds.Player);
		component.id = _id;
		addComponent(CoreComponentIds.Player, component);
	}

	public void replacePlayer(Player.ID _id) {
		Player component = createComponent(CoreComponentIds.Player);
		component.id = _id;
		replaceComponent(CoreComponentIds.Player, component);
	}

	public void removePlayer() {
		removeComponent(CoreComponentIds.Player);
	}

	public View getView() {
		return (View) getComponent(CoreComponentIds.View);
	}

	public boolean hasView() {
		return hasComponent(CoreComponentIds.View);
	}

	public void addView(Shape2D _shape) {
		View component = createComponent(CoreComponentIds.View);
		component.shape = _shape;
		addComponent(CoreComponentIds.View, component);
	}

	public void replaceView(Shape2D _shape) {
		View component = createComponent(CoreComponentIds.View);
		component.shape = _shape;
		replaceComponent(CoreComponentIds.View, component);
	}

	public void removeView() {
		removeComponent(CoreComponentIds.View);
	}

	public Motion getMotion() {
		return (Motion) getComponent(CoreComponentIds.Motion);
	}

	public boolean hasMotion() {
		return hasComponent(CoreComponentIds.Motion);
	}

	public void addMotion(Vector2 _velocity) {
		Motion component = createComponent(CoreComponentIds.Motion);
		component.velocity = _velocity;
		addComponent(CoreComponentIds.Motion, component);
	}

	public void replaceMotion(Vector2 _velocity) {
		Motion component = createComponent(CoreComponentIds.Motion);
		component.velocity = _velocity;
		replaceComponent(CoreComponentIds.Motion, component);
	}

	public void removeMotion() {
		removeComponent(CoreComponentIds.Motion);
	}
}