package com.ilargia.games.core;

import com.ilargia.games.entitas.PoolMetaData;
import com.ilargia.games.entitas.interfaces.FactoryEntity;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp. Changes to
 * this file may cause incorrect behavior and will be lost.
 * 
 * ---------------------------------------------------------------------------
 */
public class Pool extends com.ilargia.games.entitas.Pool<Entity> {

	public Pool(int totalComponents, int startCreationIndex,
			PoolMetaData metaData, FactoryEntity<Entity> factoryMethod) {
		super(totalComponents, startCreationIndex, metaData, factoryMethod);
	}
}