package com.ilargia.games.core;

import com.ilargia.games.entitas.interfaces.FactoryEntity;
import java.util.Stack;
import com.ilargia.games.entitas.interfaces.IComponent;
import com.ilargia.games.entitas.EntityMetaData;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp. Changes to
 * this file may cause incorrect behavior and will be lost.
 * 
 * ---------------------------------------------------------------------------
 */
public class Pools {

	public Pool core;

	public Pools() {
		core = createCorePool();
	}

	public Pool createCorePool() {
		return new Pool(CoreComponentIds.totalComponents, 0,
				new EntityMetaData("Core", CoreComponentIds.componentNames(),
						CoreComponentIds.componentTypes()), factoryEntity());
	}

	public Pool[] allPools() {
		return new Pool[]{core};
	}

	public FactoryEntity<Entity> factoryEntity() {
		return (int totalComponents, Stack<IComponent>[] componentPools,
				EntityMetaData entityMetaData) -> {
			return new Entity(totalComponents, componentPools, entityMetaData);
		};
	}
}