package com.ilargia.games.core;

import com.ilargia.games.entitas.Context;

import java.util.Stack;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Entitas {

    public CoreContext core;

    public Entitas() {
        core = createCoreContext();
    }

    public CoreContext createCoreContext() {
        return new CoreContext(CoreComponentIds.totalComponents, 0,
                new ContextInfo("Core", CoreComponentIds.componentNames(),
                        CoreComponentIds.componentTypes()), factoryCoreEntity());
    }

    public Context[] allContexts() {
        return new Context[]{core};
    }

    public FactoryEntity<CoreEntity> factoryCoreEntity() {
        return (int totalComponents, Stack<IComponent>[] componentContexts,
                ContextInfo contextInfo) -> {
            return new CoreEntity(totalComponents, componentContexts,
                    contextInfo);
        };
    }
}