package com.ilargia.games.core;

import com.ilargia.games.entitas.Context;
import com.ilargia.games.entitas.api.*;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Entitas implements IContexts {

	public CoreContext core;

	public Entitas() {
		core = createCoreContext();
	}

	public CoreContext createCoreContext() {
		return new CoreContext(CoreComponentsLookup.totalComponents, 0,
				new ContextInfo("Core", CoreComponentsLookup.componentNames(),
						CoreComponentsLookup.componentTypes()),
				factoryCoreEntity());
	}

	@Override
	public Context[] allContexts() {
		return new Context[]{core};
	}

	public EntityBaseFactory<CoreEntity> factoryCoreEntity() {
		return () -> {
			return new CoreEntity();
		};
	}
}