package com.ilargia.games.core;

import java.util.Stack;
import com.ilargia.games.entitas.Context;
import com.ilargia.games.entitas.api.*;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Entitas {

	public CoreContext core;

	public Entitas() {
		core = createCoreContext();
	}

	public CoreContext createCoreContext() {
		return new CoreContext(CoreComponentIds.totalComponents, 0,
				new ContextInfo("Core", CoreComponentIds.componentNames(),
						CoreComponentIds.componentTypes()), factoryCoreEntity());
	}

	public Context[] allContexts() {
		return new Context[]{core};
	}

	public EntityBaseFactory<CoreEntity> factoryCoreEntity() {
		return () -> {
			return new CoreEntity();
		};
	}
}