package com.ilargia.games.core;

import java.util.Stack;
import com.ilargia.games.entitas.Context;
import com.ilargia.games.entitas.api.*;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Entitas {

	public GameSessionContext gamesession;
	public InputContext input;
	public GameContext game;

	public Entitas() {
		gamesession = createGamesessionContext();
		input = createInputContext();
		game = createGameContext();
	}

	public GameSessionContext createGamesessionContext() {
		return new GameSessionContext(GamesessionComponentIds.totalComponents,
				0, new ContextInfo("GameSession",
						GamesessionComponentIds.componentNames(),
						GamesessionComponentIds.componentTypes()),
				factoryGameSessionEntity());
	}

	public InputContext createInputContext() {
		return new InputContext(InputComponentIds.totalComponents, 0,
				new ContextInfo("Input", InputComponentIds.componentNames(),
						InputComponentIds.componentTypes()),
				factoryInputEntity());
	}

	public GameContext createGameContext() {
		return new GameContext(GameComponentIds.totalComponents, 0,
				new ContextInfo("Game", GameComponentIds.componentNames(),
						GameComponentIds.componentTypes()), factoryGameEntity());
	}

	public Context[] allContexts() {
		return new Context[]{gamesession, input, game};
	}

	public EntityBaseFactory<GameSessionEntity> factoryGameSessionEntity() {
		return () -> {
			return new GameSessionEntity();
		};
	}

	public EntityBaseFactory<InputEntity> factoryInputEntity() {
		return () -> {
			return new InputEntity();
		};
	}

	public EntityBaseFactory<GameEntity> factoryGameEntity() {
		return () -> {
			return new GameEntity();
		};
	}
}