package com.ilargia.games.core;

import java.util.Stack;
import com.ilargia.games.entitas.Context;
import com.ilargia.games.entitas.api.*;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Entitasaaa implements IContexts {

	public GameContext game;

	public Entitasaaa() {
		game = createGameContext();
	}

	public GameContext createGameContext() {
		return new GameContext(GameComponentIds.totalComponents, 0,
				new ContextInfo("Game", GameComponentIds.componentNames(),
						GameComponentIds.componentTypes()), factoryGameEntity());
	}

	@Override
	public Context[] allContexts() {
		return new Context[]{game};
	}

	public EntityBaseFactory<GameEntity> factoryGameEntity() {
		return () -> {
			return new GameEntity();
		};
	}
}