package com.ilargia.games.core;

import com.ilargia.games.components.Score;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class GamesessionComponentIds {

	public static final int Score = 0;
	public static final int totalComponents = 1;

	public static String[] componentNames() {
		return new String[]{"Score"};
	}

	public static Class[] componentTypes() {
		return new Class[]{Score.class};
	}
}