package com.ilargia.games.core;

import com.ilargia.games.entitas.matcher.Matcher;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class GamesessionMatcher {

	private static Matcher<GameSessionEntity> _matcherScore;

	public static Matcher<GameSessionEntity> Score() {
		if (_matcherScore == null) {
			Matcher<GameSessionEntity> matcher = (Matcher) Matcher
					.AllOf(GamesessionComponentIds.Score);
			matcher.componentNames = GamesessionComponentIds.componentNames();
			_matcherScore = matcher;
		}
		return _matcherScore;
	}
}