package com.ilargia.games.core;

import com.ilargia.games.components.BurstMode;
import com.ilargia.games.components.Input;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class InputComponentIds {

	public static final int BurstMode = 1;
	public static final int Input = 5;
	public static final int totalComponents = 2;

	public static String[] componentNames() {
		return new String[]{null, "BurstMode", null, null, null, "Input", null,
				null, null, null, null};
	}

	public static Class[] componentTypes() {
		return new Class[]{null, BurstMode.class, null, null, null,
				Input.class, null, null, null, null, null};
	}
}