package com.ilargia.games.core;

import com.ilargia.games.entitas.api.*;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class RenderContext
		extends
			com.ilargia.games.entitas.Context<RenderEntity> {

	public RenderContext(int totalComponents, int startCreationIndex,
			ContextInfo contextInfo, FactoryEntity<RenderEntity> factoryMethod) {
		super(totalComponents, startCreationIndex, contextInfo, factoryMethod);
	}
}