package com.ilargia.games.core;

import com.ilargia.games.entitas.matcher.Matcher;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class RenderMatcher {

	private static Matcher _matcherTextureView;

	public static Matcher TextureView() {
		if (_matcherTextureView == null) {
			Matcher matcher = (Matcher) Matcher
					.AllOf(RenderComponentIds.TextureView);
			matcher.componentNames = RenderComponentIds.componentNames();
			_matcherTextureView = matcher;
		}
		return _matcherTextureView;
	}
}