package com.ilargia.games.core;

import com.ilargia.games.components.TextureView;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class RenderComponentIds {

	public static final int TextureView = 0;
	public static final int totalComponents = 1;

	public static String[] componentNames() {
		return new String[]{"TextureView"};
	}

	public static Class[] componentTypes() {
		return new Class[]{TextureView.class};
	}
}