package com.ilargia.games.core;

import com.ilargia.games.entitas.matcher.Matcher;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class ScoreMatcher {

	private static Matcher _matcherScore;

	public static Matcher Score() {
		if (_matcherScore == null) {
			Matcher matcher = (Matcher) Matcher.AllOf(ScoreComponentIds.Score);
			matcher.componentNames = ScoreComponentIds.componentNames();
			_matcherScore = matcher;
		}
		return _matcherScore;
	}
}