package com.ilargia.games.core;

import com.ilargia.games.entitas.api.*;
import com.ilargia.games.entitas.Entity;
import java.util.Stack;
import com.ilargia.games.components.Score;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class ScoreEntity extends Entity {

	public ScoreEntity(int totalComponents,
			Stack<IComponent>[] componentContexts, ContextInfo contextInfo) {
		super(totalComponents, componentContexts, contextInfo);
	}

	public Score getScore() {
		return (Score) getComponent(ScoreComponentIds.Score);
	}

	public boolean hasScore() {
		return hasComponent(ScoreComponentIds.Score);
	}

	public ScoreEntity addScore(int value) {
		Score component = (Score) recoverComponent(ScoreComponentIds.Score);
		if (component == null) {
			component = new Score();
		}
		component.value = value;
		addComponent(ScoreComponentIds.Score, component);
		return this;
	}

	public ScoreEntity replaceScore(int value) {
		Score component = (Score) recoverComponent(ScoreComponentIds.Score);
		if (component == null) {
			component = new Score();
		}
		component.value = value;
		removeComponent(ScoreComponentIds.Score);
		return this;
	}

	public ScoreEntity removeScore() {
		removeComponent(ScoreComponentIds.Score);
		return this;
	}
}