package com.ilargia.games.core.state;

import com.ilargia.games.entitas.matcher.Matcher;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class GamestateMatcher {

	private static Matcher _matcherScore;

	public static Matcher Score() {
		if (_matcherScore == null) {
			Matcher matcher = (Matcher) Matcher
					.AllOf(GamestateComponentIds.Score);
			matcher.componentNames = GamestateComponentIds.componentNames();
			_matcherScore = matcher;
		}
		return _matcherScore;
	}
}