package com.ilargia.games.core.state;

import com.ilargia.games.entitas.api.*;
import com.ilargia.games.entitas.Entity;
import java.util.Stack;
import com.ilargia.games.components.state.Score;
import com.ilargia.games.entitas.api.IComponent;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class GameStateEntity extends Entity {

	public GameStateEntity() {
	}

	public Score getScore() {
		return (Score) getComponent(GamestateComponentsLookup.Score);
	}

	public boolean hasScore() {
		return hasComponent(GamestateComponentsLookup.Score);
	}

	public GameStateEntity addScore(int value) {
		Score component = (Score) recoverComponent(GamestateComponentsLookup.Score);
		if (component == null) {
			component = new Score();
		}
		component.value = value;
		addComponent(GamestateComponentsLookup.Score, component);
		return this;
	}

	public GameStateEntity replaceScore(int value) {
		Score component = (Score) recoverComponent(GamestateComponentsLookup.Score);
		if (component == null) {
			component = new Score();
		}
		component.value = value;
		replaceComponent(GamestateComponentsLookup.Score, component);
		return this;
	}

	public GameStateEntity removeScore() {
		removeComponent(GamestateComponentsLookup.Score);
		return this;
	}
}