package com.ilargia.games.entitas.utils;

import com.ilargia.games.entitas.interfaces.FactoryEntity;
import java.util.Stack;
import com.ilargia.games.entitas.interfaces.IComponent;
import com.ilargia.games.entitas.EntityMetaData;
import com.ilargia.games.entitas.events.EventBus;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Context {

	public Pool test;
	public Pool test2;
	public EventBus<Entity> bus;

	public Context() {
		test = createTestPool();
		test2 = createTest2Pool();
		bus = new EventBus<>();
	}

	public Pool createTestPool() {
		return new Pool(TestComponentIds.totalComponents, 0,
				new EntityMetaData("Test", TestComponentIds.componentNames(),
						TestComponentIds.componentTypes()), factoryEntity(),
				bus);
	}

	public Pool createTest2Pool() {
		return new Pool(Test2ComponentIds.totalComponents, 0,
				new EntityMetaData("Test2", Test2ComponentIds.componentNames(),
						Test2ComponentIds.componentTypes()), factoryEntity(),
				bus);
	}

	public Pool[] allPools() {
		return new Pool[]{test, test2};
	}

	public FactoryEntity<Entity> factoryEntity() {
		return (int totalComponents, Stack<IComponent>[] componentPools,
				EntityMetaData entityMetaData) -> {
			return new Entity(totalComponents, componentPools, entityMetaData,
					bus);
		};
	}
}