package com.ilargia.games.entitas.utils;

import com.ilargia.games.entitas.api.ContextInfo;
import com.ilargia.games.entitas.api.FactoryEntity;

import java.util.*;

import com.ilargia.games.entitas.api.IComponent;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Context {

	public Pool test;
	public Pool test2;

	public Context() {
		test = createTestPool();
		test2 = createTest2Pool();

	}

	public Pool createTestPool() {
		return new Pool(TestComponentIds.totalComponents, 0,
				new ContextInfo("Test", TestComponentIds.componentNames(),
						TestComponentIds.componentTypes()), factoryEntity());
	}

	public Pool createTest2Pool() {
		return new Pool(Test2ComponentIds.totalComponents, 0,
				new ContextInfo("Test2", Test2ComponentIds.componentNames(),
						Test2ComponentIds.componentTypes()), factoryEntity());
	}

	public Pool[] allPools() {
		return new Pool[]{test, test2};
	}

	public FactoryEntity<Entity> factoryEntity() {
		return (int totalComponents, Stack<IComponent>[] componentPools,
				ContextInfo contextInfo) -> {
			return new Entity(totalComponents, componentPools, contextInfo);
		};
	}
}