package com.ilargia.games.entitas.utils;

import com.ilargia.games.entitas.Context;
import com.ilargia.games.entitas.api.ContextInfo;
import com.ilargia.games.entitas.api.FactoryEntity;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Pool extends Context<Entity> {

	public Pool(int totalComponents, int startCreationIndex,
				ContextInfo metaData, FactoryEntity<Entity> factoryMethod) {
		super(totalComponents, startCreationIndex, metaData, factoryMethod);
	}

	public Entity getPlayerEntity() {
		return getGroup(TestMatcher.Player()).getSingleEntity();
	}

	public boolean isPlayer() {
		return getPlayerEntity() != null;
	}

	public Pool setPlayer(boolean value) {
		Entity entity = getPlayerEntity();
		if (value != (entity != null)) {
			if (value) {
				entity.setPlayer(true);
			} else {
				destroyEntity(entity);
			}
		}
		return this;
	}
}