package com.ilargia.games.entitas.utils;

import com.ilargia.games.entitas.components.Player;
import com.ilargia.games.entitas.components.Interactive;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Test2ComponentIds {

	public static final int Player = 0;
	public static final int Interactive = 2;
	public static final int totalComponents = 2;

	public static String[] componentNames() {
		return new String[]{"Player", null, "Interactive", null, null, null};
	}

	public static Class[] componentTypes() {
		return new Class[]{Player.class, null, Interactive.class, null, null,
				null};
	}
}