package com.ilargia.games.entitas.utils;

import com.ilargia.games.entitas.components.Player;
import com.ilargia.games.entitas.components.View;
import com.ilargia.games.entitas.components.Interactive;
import com.ilargia.games.entitas.components.Position;
import com.ilargia.games.entitas.components.Motion;
import com.ilargia.games.entitas.components.Score;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class TestComponentIds {

	public static final int Player = 0;
	public static final int View = 1;
	public static final int Interactive = 2;
	public static final int Position = 3;
	public static final int Motion = 4;
	public static final int Score = 5;
	public static final int totalComponents = 6;

	public static String[] componentNames() {
		return new String[]{"Player", "View", "Interactive", "Position",
				"Motion", "Score"};
	}

	public static Class[] componentTypes() {
		return new Class[]{Player.class, View.class, Interactive.class,
				Position.class, Motion.class, Score.class};
	}
}