package com.ilargia.games.entitas.utils;

import com.ilargia.games.entitas.interfaces.IMatcher;
import com.ilargia.games.entitas.matcher.Matcher;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class TestMatcher {

	private static IMatcher _matcherInteractive;
	private static IMatcher _matcherScore;
	private static IMatcher _matcherPosition;
	private static IMatcher _matcherPlayer;
	private static IMatcher _matcherView;
	private static IMatcher _matcherMotion;

	public static IMatcher Interactive() {
		if (_matcherInteractive == null) {
			Matcher matcher = (Matcher) Matcher
					.AllOf(TestComponentIds.Interactive);
			matcher.componentNames = TestComponentIds.componentNames();
			_matcherInteractive = matcher;
		}
		return _matcherInteractive;
	}

	public static IMatcher Score() {
		if (_matcherScore == null) {
			Matcher matcher = (Matcher) Matcher.AllOf(TestComponentIds.Score);
			matcher.componentNames = TestComponentIds.componentNames();
			_matcherScore = matcher;
		}
		return _matcherScore;
	}

	public static IMatcher Position() {
		if (_matcherPosition == null) {
			Matcher matcher = (Matcher) Matcher
					.AllOf(TestComponentIds.Position);
			matcher.componentNames = TestComponentIds.componentNames();
			_matcherPosition = matcher;
		}
		return _matcherPosition;
	}

	public static IMatcher Player() {
		if (_matcherPlayer == null) {
			Matcher matcher = (Matcher) Matcher.AllOf(TestComponentIds.Player);
			matcher.componentNames = TestComponentIds.componentNames();
			_matcherPlayer = matcher;
		}
		return _matcherPlayer;
	}

	public static IMatcher View() {
		if (_matcherView == null) {
			Matcher matcher = (Matcher) Matcher.AllOf(TestComponentIds.View);
			matcher.componentNames = TestComponentIds.componentNames();
			_matcherView = matcher;
		}
		return _matcherView;
	}

	public static IMatcher Motion() {
		if (_matcherMotion == null) {
			Matcher matcher = (Matcher) Matcher.AllOf(TestComponentIds.Motion);
			matcher.componentNames = TestComponentIds.componentNames();
			_matcherMotion = matcher;
		}
		return _matcherMotion;
	}
}