package com.ilargia.games.entitas.utils;

import com.ilargia.games.entitas.matcher.Matcher;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class TestMatcher {

    private static Matcher _matcherInteractive;
    private static Matcher _matcherMotion;
    private static Matcher _matcherPlayer;
    private static Matcher _matcherPosition;
    private static Matcher _matcherScore;
    private static Matcher _matcherView;

    public static Matcher Interactive() {
        if (_matcherInteractive == null) {
            Matcher matcher = (Matcher) Matcher
                    .AllOf(TestComponentIds.Interactive);
            matcher.componentNames = TestComponentIds.componentNames();
            _matcherInteractive = matcher;
        }
        return _matcherInteractive;
    }

    public static Matcher Motion() {
        if (_matcherMotion == null) {
            Matcher matcher = (Matcher) Matcher.AllOf(TestComponentIds.Motion);
            matcher.componentNames = TestComponentIds.componentNames();
            _matcherMotion = matcher;
        }
        return _matcherMotion;
    }

    public static Matcher Player() {
        if (_matcherPlayer == null) {
            Matcher matcher = (Matcher) Matcher.AllOf(TestComponentIds.Player);
            matcher.componentNames = TestComponentIds.componentNames();
            _matcherPlayer = matcher;
        }
        return _matcherPlayer;
    }

    public static Matcher Position() {
        if (_matcherPosition == null) {
            Matcher matcher = (Matcher) Matcher
                    .AllOf(TestComponentIds.Position);
            matcher.componentNames = TestComponentIds.componentNames();
            _matcherPosition = matcher;
        }
        return _matcherPosition;
    }

    public static Matcher Score() {
        if (_matcherScore == null) {
            Matcher matcher = (Matcher) Matcher.AllOf(TestComponentIds.Score);
            matcher.componentNames = TestComponentIds.componentNames();
            _matcherScore = matcher;
        }
        return _matcherScore;
    }

    public static Matcher View() {
        if (_matcherView == null) {
            Matcher matcher = (Matcher) Matcher.AllOf(TestComponentIds.View);
            matcher.componentNames = TestComponentIds.componentNames();
            _matcherView = matcher;
        }
        return _matcherView;
    }
}