package com.ilargia.games.entitas.utils;

import com.ilargia.games.entitas.interfaces.IMatcher;
import com.ilargia.games.entitas.matcher.Matcher;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Test2Matcher {

	private static IMatcher _matcherInteractive;
	private static IMatcher _matcherPlayer;

	public static IMatcher Interactive() {
		if (_matcherInteractive == null) {
			Matcher matcher = (Matcher) Matcher
					.AllOf(Test2ComponentIds.Interactive);
			matcher.componentNames = Test2ComponentIds.componentNames();
			_matcherInteractive = matcher;
		}
		return _matcherInteractive;
	}

	public static IMatcher Player() {
		if (_matcherPlayer == null) {
			Matcher matcher = (Matcher) Matcher.AllOf(Test2ComponentIds.Player);
			matcher.componentNames = Test2ComponentIds.componentNames();
			_matcherPlayer = matcher;
		}
		return _matcherPlayer;
	}
}