package ilargia.entitas.utils;

import ilargia.entitas.matcher.Matcher;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Test2Matcher {

    private static Matcher _matcherInteractive;
    private static Matcher _matcherPlayer;

    public static Matcher Interactive() {
        if (_matcherInteractive == null) {
            Matcher matcher = (Matcher) Matcher
                    .AllOf(Test2ComponentIds.Interactive);
            matcher.componentNames = Test2ComponentIds.componentNames();
            _matcherInteractive = matcher;
        }
        return _matcherInteractive;
    }

    public static Matcher Player() {
        if (_matcherPlayer == null) {
            Matcher matcher = (Matcher) Matcher.AllOf(Test2ComponentIds.Player);
            matcher.componentNames = Test2ComponentIds.componentNames();
            _matcherPlayer = matcher;
        }
        return _matcherPlayer;
    }
}