package ilargia.entitas.utils;

import ilargia.entitas.components.*;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class TestComponentIds {

    public static final int Interactive = 0;
    public static final int Motion = 1;
    public static final int Player = 2;
    public static final int Position = 3;
    public static final int Score = 4;
    public static final int View = 5;
    public static final int totalComponents = 6;

    public static String[] componentNames() {
        return new String[]{"Interactive", "Motion", "Player", "Position",
                "Score", "View"};
    }

    public static Class[] componentTypes() {
        return new Class[]{Interactive.class, ilargia.entitas.components.Motion.class, ilargia.entitas.components.Player.class,
                ilargia.entitas.components.Position.class, ilargia.entitas.components.Score.class, ilargia.entitas.components.View.class};
    }
}