package ilargia.entitas.utils;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Test2ComponentIds {

    public static final int Interactive = 0;
    public static final int Player = 2;
    public static final int totalComponents = 2;

    public static String[] componentNames() {
        return new String[]{"Interactive", null, "Player", null, null, null};
    }

    public static Class[] componentTypes() {
        return new Class[]{ilargia.entitas.components.Interactive.class, null, ilargia.entitas.components.Player.class, null, null,
                null};
    }
}