package com.ilargia.games.entitas.codeGeneration.plugins.postProcessors;


import com.ilargia.games.entitas.codeGeneration.CodeGenFile;
import com.ilargia.games.entitas.codeGeneration.interfaces.ICodeGenFilePostProcessor;

import java.util.List;

public class AddFileHeaderPostProcessor implements ICodeGenFilePostProcessor {

    public static String AUTO_GENERATED_HEADER_FORMAT =
            "    //------------------------------------------------------------------------------" +
                    "// <auto-generated>" +
                    "//     This code was generated by {0}." +
                    "//" +
                    "//     Changes to this file may cause incorrect behavior and will be lost if" +
                    "//     the code is regenerated." +
                    "// </auto-generated>" +
                    "//------------------------------------------------------------------------------"


    @Override
    public String getName() {
        return "Add file header";
    }

    @Override
    public Integer gePriority() {
        return 0;
    }

    @Override
    public boolean isEnableByDefault() {
        return true;
    }

    @Override
    public boolean runInDryMode() {
        return true;
    }

    @Override
    public List<CodeGenFile> postProcess(List<CodeGenFile> files) {
        for (CodeGenFile file : files) {
            file.fileContent.ja = String.format(AUTO_GENERATED_HEADER_FORMAT, file.generatorName) + file.fileContent;
        }


        return files;
    }

}
